SET GLOBAL sql_mode = '';

USE hangman;

CREATE TABLE IF NOT EXISTS `Words` (
  `Word_ID` INT NOT NULL AUTO_INCREMENT,
  `Word` VARCHAR(20) NOT NULL,
  `length` INT NOT NULL,
  PRIMARY KEY (`Word_ID`),

CREATE TABLE IF NOT EXISTS`Guesses` (
  `Guess_ID` INT NOT NULL AUTO_INCREMENT,
  `Guess` VARCHAR(1) NOT NULL,
  `Word_ID` INT NOT NULL,
  `Correct` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Guess_ID`),
  FOREIGN KEY (Word_ID) REFERENCES Words(Word_ID))

CREATE TABLE IF NOT EXISTS`Games` (
  `Game_ID` INT NOT NULL AUTO_INCREMENT,
  `Word_ID` INT NOT NULL,
  `Guess_ID` INT NOT NULL,
  PRIMARY KEY (`Guess_ID`),
  FOREIGN KEY (Word_ID) REFERENCES Words(Word_ID))
  FOREIGN KEY (Guess_ID) REFERENCES Guesses(Guess_ID))