DROP TABLE IF EXISTS Words;
CREATE TABLE IF NOT EXISTS Words(
  Word_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Word VARCHAR(20) NOT NULL,
  Length INTEGER NOT NULL
  );

DROP TABLE IF EXISTS Guesses;
CREATE TABLE IF NOT EXISTS Guesses (
  Guess_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Guess VARCHAR(1) NOT NULL,
  Word_ID INTEGER NOT NULL,
  Correct TINYINT(1) NOT NULL,
  FOREIGN KEY (Word_ID) REFERENCES Words(Word_ID)
  );

DROP TABLE IF EXISTS Games;
CREATE TABLE IF NOT EXISTS Games (
  Game_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Word_ID INTEGER NOT NULL,
  Guess_ID INTEGER NOT NULL,
  FOREIGN KEY (Word_ID) REFERENCES Words(Word_ID),
  FOREIGN KEY (Guess_ID) REFERENCES Guesses(Guess_ID)
  );