DROP TABLE IF EXISTS Words;
CREATE TABLE IF NOT EXISTS Words(
  Word_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Word VARCHAR(20) NOT NULL,
  Length INTEGER NOT NULL
  );

DROP TABLE IF EXISTS Games;
CREATE TABLE IF NOT EXISTS Games (
  Game_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Word_ID INTEGER NOT NULL,
  Status VARCHAR(20),
  No_Of_Guesses INTEGER NOT NULL,
  FOREIGN KEY (Word_ID) REFERENCES Words(Word_ID)
  );